### ISSUE TITLE
Is it possible to use wildcard in the flycheck-erlang-lib-path

### ISSUE THREAD

**Issue by liuzhen** [yzprofile/emacs.d#1]
I suppose it is not, but is there another way of using function rather than seq it?

**Comment by yzprofile** [comment]
You can do it in `erlang-mode-hook`. get current dir or even parse the rebar.config, and setq the `path`

**Comment by liuzhen** [comment]
I have tried replacing the setq in the `erlang-after-load-hook`
`mapcar (lambda (x) (concat x "/ebin")) (directory-files "../_build/default/lib/" "" ".")`

which should works with rebar3, but still cannot find the custom behaviour, any ideas?

**Comment by liuzhen** [comment]
I see it, the variable is `flycheck-erlang-library-path`, you will need to corrent your gist file, if I got it right ;-)
